import Header from "@/components/Navigation/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Navigation/Footer";
import { UserContextProvider } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <UserContextProvider>{children}</UserContextProvider>
        </div>
      </body>
    </html>
  );
}
